# Generated by Django 3.2.4 on 2021-06-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iShoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metalshoe',
            name='type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='no',
            field=models.IntegerField(),
        ),
    ]
