# Generated by Django 3.2.4 on 2021-06-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iShoe', '0002_auto_20210608_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=8)),
                ('shoeid', models.ManyToManyField(to='iShoe.MetalShoe')),
            ],
        ),
    ]
